# Generated by Django 3.2.11 on 2022-03-27 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_combustibles_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combustibles',
            old_name='dieselTamem_2019',
            new_name='tamem_2019',
        ),
        migrations.RenameField(
            model_name='combustibles',
            old_name='dieselTamem_2020',
            new_name='tamem_2020',
        ),
        migrations.RenameField(
            model_name='combustibles',
            old_name='dieselTamem_2021',
            new_name='tamem_2021',
        ),
        migrations.RenameField(
            model_name='combustibles',
            old_name='dieselTamem_2022',
            new_name='tamem_2022',
        ),
    ]
