# Generated by Django 3.2.11 on 2022-04-07 11:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_date_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date_app',
            name='date_now',
        ),
        migrations.AddField(
            model_name='date_app',
            name='date_finish',
            field=models.DateField(default=datetime.datetime(2011, 11, 4, 0, 5, 23), null=True),
        ),
        migrations.AddField(
            model_name='date_app',
            name='days_remaning',
            field=models.PositiveIntegerField(blank=True, default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='date_app',
            name='maintenance_interval',
            field=models.PositiveIntegerField(blank=True, default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='date_app',
            name='tender_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='date_app',
            name='tender_number',
            field=models.TextField(blank=True),
        ),
    ]
