# Generated by Django 3.2.11 on 2022-04-07 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20220407_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date_app',
            name='date_finish',
            field=models.DateField(default=datetime.datetime(2011, 11, 4, 0, 5, 23)),
        ),
    ]
