# Generated by Django 3.2.11 on 2022-04-07 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_alter_date_app_date_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date_app',
            name='date_finish',
            field=models.DateField(default=datetime.datetime(2022, 11, 4, 0, 5, 23)),
        ),
        migrations.AlterField(
            model_name='date_app',
            name='days_remaning',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='date_app',
            name='maintenance_interval',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='date_app',
            name='tender_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='date_app',
            name='tender_number',
            field=models.TextField(),
        ),
    ]
