# Generated by Django 3.2 on 2022-04-12 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_auto_20220407_0431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='date_app',
            old_name='date_finish',
            new_name='date_maintenance',
        ),
        migrations.RemoveField(
            model_name='date_app',
            name='days_remaning',
        ),
        migrations.AddField(
            model_name='date_app',
            name='concractor_name',
            field=models.TextField(default='ahmed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='date_app',
            name='date_work',
            field=models.DateField(default=datetime.datetime(2022, 11, 4, 0, 5, 23)),
        ),
    ]
