# Generated by Django 3.2.11 on 2022-05-10 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_alter_date_app_maintenance_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='monthlyReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('date_work', models.DateField(default=datetime.datetime(2022, 11, 4, 0, 5, 23))),
                ('area', models.CharField(max_length=255)),
                ('work', models.TextField()),
            ],
        ),
    ]
