# Generated by Django 3.2.11 on 2022-05-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_monthlyreportmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreportmodel',
            name='image',
            field=models.FileField(blank=True, upload_to='monthlyReport/'),
        ),
    ]
