# Generated by Django 3.2.11 on 2022-05-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_monthlyreportmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreportmodel',
            name='month',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyreportmodel',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
