# Generated by Django 3.2.11 on 2022-05-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_auto_20220515_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreportmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/monthlyReport/'),
        ),
    ]
