# Generated by Django 3.2.11 on 2022-05-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_alter_monthlyreportmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyreportmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='monthlyreportmodel',
            name='photo',
            field=models.FileField(blank=True, upload_to='monthlyReport/'),
        ),
    ]
