# Generated by Django 3.2.11 on 2022-05-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_auto_20220516_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreportmodel',
            name='code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
