# Generated by Django 3.2.11 on 2022-05-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_monthlyreportmodel_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreportmodel',
            name='code',
            field=models.IntegerField(default=1),
        ),
    ]
