# Generated by Django 3.2 on 2022-06-22 07:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_alter_monthlyreportmodel_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('date_sumbmittion', models.DateField(default=datetime.datetime(2022, 11, 4, 0, 5, 23))),
                ('speed', models.CharField(max_length=255)),
                ('difficulty', models.CharField(max_length=255)),
                ('assessment', models.IntegerField()),
                ('note', models.CharField(max_length=500)),
            ],
        ),
    ]
