# Generated by Django 3.2 on 2022-06-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_questionnairemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnairemodel',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='questionnairemodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='questionnairemodel',
            name='note',
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='application',
            field=models.CharField(default='وزارة الاشغال', max_length=255),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='improvment',
            field=models.CharField(default='وزارة الاشغال', max_length=500),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='institution',
            field=models.CharField(default='وزارة الاشغال', max_length=255),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='usage',
            field=models.CharField(default='هل تستخدم التطبيق', max_length=255),
        ),
        migrations.AddField(
            model_name='questionnairemodel',
            name='user',
            field=models.CharField(default='وزارة الاشغال', max_length=255),
        ),
        migrations.AlterField(
            model_name='questionnairemodel',
            name='difficulty',
            field=models.CharField(default='وزارة الاشغال', max_length=255),
        ),
        migrations.AlterField(
            model_name='questionnairemodel',
            name='speed',
            field=models.CharField(default='وزارة الاشغال', max_length=255),
        ),
    ]
