# Generated by Django 3.2.3 on 2021-06-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='localRoadsDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenName', models.CharField(max_length=200)),
                ('requestNumber', models.CharField(max_length=200)),
                ('requestDate', models.DateTimeField()),
                ('landNumber', models.PositiveIntegerField()),
                ('basinName', models.CharField(max_length=200)),
                ('basinNumber', models.PositiveIntegerField()),
                ('village', models.CharField(max_length=200)),
                ('roadLength', models.PositiveIntegerField()),
                ('roadWidth', models.PositiveIntegerField()),
                ('report', models.CharField(max_length=200)),
                ('landSubgrade', models.CharField(max_length=200)),
            ],
        ),
    ]
