# Generated by Django 3.2.3 on 2021-06-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectOne', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localroadsdatabase',
            name='heavyEquipment',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
