# Generated by Django 2.2.5 on 2021-06-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectOne', '0002_localroadsdatabase_heavyequipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localroadsdatabase',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
