# Generated by Django 2.2.5 on 2021-06-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectOne', '0003_auto_20210605_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localroadsdatabase',
            name='requestDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
