# Generated by Django 3.2.3 on 2021-06-06 09:11

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projectOne', '0004_auto_20210605_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localroadsdatabase',
            name='heavyEquipment',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('لودر', 'لودر'), ('جك همر', 'جك همر'), ('قلاب', 'قلاب'), ('جريدير', 'جريدر')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='localroadsdatabase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='localroadsdatabase',
            name='landSubgrade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='localroadsdatabase',
            name='report',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='localroadsdatabase',
            name='roadLength',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='localroadsdatabase',
            name='roadWidth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
