# Generated by Django 3.2.3 on 2021-06-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectOne', '0005_auto_20210606_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localroadsdatabase',
            name='heavyEquipment',
            field=models.CharField(blank=True, choices=[('لودر', 'لودر'), ('جك همر', 'جك همر'), ('قلاب', 'قلاب'), ('جريدير', 'جريدر')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='localroadsdatabase',
            name='landSubgrade',
            field=models.CharField(blank=True, choices=[('تربة حمراء', 'تربة حمراء'), ('صخرية', 'صخرية')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='localroadsdatabase',
            name='village',
            field=models.CharField(choices=[('مادبا', 'مادبا'), ('ماعين', 'ماعين'), ('الفحياء', 'الفيحاء'), ('الفيصلية', 'الفيصلية'), ('جرينة', 'جرينة'), ('الخطابية', 'الخطابية'), ('خربة الهلالية', 'خربة الهلالية'), ('الواحة', 'الواحة'), ('جبيل', 'جبيل'), ('خربة سطيحة', 'خربة سطيحة'), ('خربة حنينا', 'خربة حنينا'), ('كفير ابو خنينان الشريق', 'كفير ابو خنينان الشرقي')], max_length=200),
        ),
    ]
