# Generated by Django 3.2.3 on 2021-06-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectOne', '0007_alter_localroadsdatabase_requestdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localroadsdatabase',
            name='report',
            field=models.CharField(blank=True, choices=[('يوجد تقرير مساح مرخص', 'يوجد تقرير مساح مرخص'), ('لا يوجد تقرير مساح مرخص', 'لا يوجد تقرير مساح مرخص')], max_length=200, null=True),
        ),
    ]
