# Generated by Django 3.2.3 on 2021-06-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectOne', '0008_alter_localroadsdatabase_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='localroadsdatabase',
            name='service',
            field=models.CharField(blank=True, choices=[('بيوت', 'بيوت'), ('اراضي', 'اراضي'), ('مزارع', 'مزارع')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='localroadsdatabase',
            name='heavyEquipment',
            field=models.CharField(blank=True, choices=[('لودر', 'لودر'), ('جك همر', 'جك همر'), ('قلاب', 'قلاب'), ('جريدير', 'جريدر'), ('قلاب + تنك مياه ', ' قلاب + تنك مياه')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='localroadsdatabase',
            name='report',
            field=models.CharField(blank=True, choices=[(' يوجد تقرير مساح مرخص  ', ' يوجد تقرير مساح مرخص '), (' لا يوجد تقرير مساح مرخص    ', ' لا يوجد تقرير مساح مرخص ')], max_length=200, null=True),
        ),
    ]
