# Generated by Django 3.2.3 on 2021-06-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectOne', '0009_auto_20210608_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='localroadsdatabase',
            name='tendiring',
            field=models.CharField(blank=True, choices=[('الفرشيات', 'الفرشيات'), ('سيل كوت', 'سيل كوت'), ('تعبيد', 'تعبيد')], max_length=100, null=True),
        ),
    ]
