# Generated by Django 3.2.3 on 2021-06-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectOne', '0010_localroadsdatabase_tendiring'),
    ]

    operations = [
        migrations.AddField(
            model_name='localroadsdatabase',
            name='currentLayer',
            field=models.CharField(blank=True, choices=[('غير مفتوحة', 'غير مفتوحة'), ('طمم', 'طمم'), ('فرشيات', 'فرشيات'), ('سيل كوت متاكل_اعادة انشاء', 'سيل كوت متاكل_اعادة انشاء'), ('خلطة متاكلة_اعادة انشاء', 'خلطة متاكلة_اعادة انشاء')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='localroadsdatabase',
            name='event',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
