# Generated by Django 2.2.5 on 2021-07-08 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectOne', '0013_auto_20210622_1856'),
        ('projectOne', '0013_auto_20210622_0026'),
    ]

    operations = [
    ]
