# Generated by Django 2.2.5 on 2021-08-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectOne', '0014_merge_20210708_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='localroadsdatabase',
            name='land_chart',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='localroadsdatabase',
            name='survy_report',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
