# Generated by Django 2.2.5 on 2021-08-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectOne', '0015_auto_20210822_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localroadsdatabase',
            name='land_chart',
            field=models.ImageField(blank=True, upload_to='projectOne\\static\\images'),
        ),
        migrations.AlterField(
            model_name='localroadsdatabase',
            name='survy_report',
            field=models.ImageField(blank=True, upload_to='projectOne\\static\\images'),
        ),
    ]
