# Generated by Django 2.2.5 on 2021-08-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectOne', '0016_auto_20210822_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localroadsdatabase',
            name='land_chart',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='localroadsdatabase',
            name='survy_report',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
