# Generated by Django 2.2.5 on 2021-08-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectOne', '0017_auto_20210822_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localroadsdatabase',
            name='land_chart',
            field=models.ImageField(blank=True, null=True, upload_to='mywork3\\projectOne\\static'),
        ),
    ]
