# Generated by Django 2.2.5 on 2021-09-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectOne', '0019_auto_20210822_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localroadsdatabase',
            name='land_chart',
            field=models.FileField(blank=True, null=True, upload_to='pdfFile/'),
        ),
        migrations.AlterField(
            model_name='localroadsdatabase',
            name='survy_report',
            field=models.FileField(blank=True, null=True, upload_to='pdfFile/'),
        ),
    ]
